"""
    Module name:- 0002_alter_allocation_release_date
"""


# Generated by Django 4.2.9 on 2024-03-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    """
        Migration class.
    """

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
