# Generated by Django 4.2.9 on 2024-03-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_allocation_slug_alter_equipment_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocation",
            name="slug",
        ),
    ]
